### ISSUE TITLE
How set Parameters

### ISSUE THREAD

**Issue by Black-di** [Demion/nvapioc#1]
Hi,

I don't know much about code. I just want to execute the “.exe” directly, but I don't know how to set the parameters. Can you give a sample of the settings? Thanks a lot!

**Comment by Demion** [comment]
Create **bat**ch file same as you are doing for miner. 
Tell me what values you want to overclock, I can give you example then.
Other than that all parameters are described in **Usage:** at _README.md_.

**Comment by Black-di** [comment]
For example, set the memory frequency. The parameter after "-mem" is "gpuBusId" "pState" "frequencyKHz". However, I don't know what the value of "gpuBusId" "pState" should be.

**Comment by Demion** [comment]
**pState** is GPU P-State. 
For NVIDIA it is usually 0 or 2 under load. You can check in NVIDIA Inspector (check under load). 
For AMD I cant tell for sure (probably 7 for core 2 or 3 for memory) cause I dont have any AMD right now but you can also check using OverdriveNTool (usually highest number under load, not lowest as NVIDIA).

**gpuBusId** is GPU PCI Bus ID. 
You can check Device Manager - Display Adapters - Properties - General - Location - PCI Bus.

**frequencyKHz** is in kHz, so +150 would be 150000. For AMD same but absolute value (not relative as NVIDIA).

**Comment by Black-di** [comment]
Thanks for your help, it works well.

**Comment by ghost** [comment]
So if I was setting multiple cards and my memory reads in MHz, and I would like to go from 5000Mhz, would it be like -mem 0 0 5500000? And then for gpu 0 and 1, -mem 0 0 5500000, 1 0 5500000?

**Comment by Demion** [comment]
`-mem 0 0 5500000 -mem 1 0 5500000`

But keep in mind, NVIDIA P-State is 0 or 2, but relative kHz (500000), AMD P-State is 2 or 3, but absolute kHz (5500000); also use PCI Bus, not GPU index.

**Comment by ghost** [comment]
Ah okay. For nvidia do I set the frequency is ant to achieve or the variable it take to achieve a certain frequency?

**Comment by ghost** [comment]
As in relative I would set p state 0 and the clock to say reach 2000MHz from 1545MHz and mem 5000Mhz to 5500Mhz I would set parameters as -cclock  0 0 455000 -mem 0 0 500000?

**Comment by ghost** [comment]
Also for keeping my setup easy to glance at within script can I

#GPU0
-cclock 0 0 455000 -mem 0 0 500000

#GPU1
-cclock 0 0 600000 -mem 0 0 500000

**Comment by Demion** [comment]
NVIDIA frequency is relative offset from base clock, 500000 will be +500 MHz.
You can try using variables in batch file.
```
SET GPU0= -core 0 0 455000 -mem 0 0 500000
SET GPU1= -core 1 0 600000 -mem 1 0 500000
nvapioc %GPU0% %GPU1%
```

**Comment by ghost** [comment]
Okay, one last question I promise, how does the fan parameter work? If I want all fans on say 80% always

**Comment by Demion** [comment]
It will be `-fan 0 0 80 -fan 1 0 80` and so on for each GPU.
But it is not working on new NVIDIA cards starting from 20 series, I think, not sure about new AMD cards. I plan to fix it soon.

**Comment by ghost** [comment]
Ah lol I feel stupid, so still (busid) (pstate) (desired percentage)

It's fine, I have two rigs of 8 1080 ti so it should work.

**Comment by Demion** [comment]
It is actually `BusID FanIndex Speed%`.
But fan index is mostly 0 and controls all fans, in rare cases you may need to specify for each fan.
-1 speed will reset to default (auto).
