### ISSUE TITLE
Whether there are use parameter examples?

### ISSUE THREAD

**Issue by zangjiahe** [Demion/nvapioc#10]
What is an example of card A and card N?
My own tool set using the vs2017 platform is v140
Compiled to run (nvapioc.exe-AMD-core 8 0 10000)
Hint: Invalid parameter #3 "8"
Invalid parameter #4 "0"
Invalid parameter #5 "10000"
Using the releases version of the repository will not report the error above, but again there will be no response, and the log will output the following:
"[02.02.2023 16:55:39][main.cpp:0344] nvapi = LoadLibraryA(nvapiDllName)                      0                    (0x00000000)"
Is there a correct AMD graphics card and NVIDIA graphics card overclocking sample parameters? Thanks!

**Comment by Demion** [comment]
I don't have any AMD card for a long time, but, as far as I remember :
1. For Nvidia only GPU use `-nvidia 1 -amd 0`, for AMD only GPU use `-nvidia 0 -amd 1`, for both use `-nvidia 1 -amd 1`.
2. GPU PCI Bus ID you can check Device Manager - Display Adapters - Properties - General - Location - PCI Bus.
3. Nvidia P-State is 0 or 2, AMD P-State is 2 or 3. 
4. Nvidia frequency is relative offset from base clock, 100000 will be +100 MHz, AMD frequency is absolute value, 1000000  will be 1000 MHz.

Working example for my Nvidia GPU at PCI Bus ID 1, +100 MHz core, +500 MHz memory:
`nvapioc.exe -nvidia 1 -amd 0 -core 1 0 100000 -mem 1 0 500000`

Update: 
AMD core P-State (can be 1, 2, 3) and memory P-State (can be 7) is different, you can check with OverdriveNTool. 
Nvidia P-State almost always will be 0, you can check with NVIDIA Inspector. 
Tools links in ReadMe.

**Comment by 1usmus** [comment]
> I don't have any AMD card for a long time, but, as far as I remember :
> 
> 1. For Nvidia only GPU use `-nvidia 1 -amd 0`, for AMD only GPU use `-nvidia 0 -amd 1`, for both use `-nvidia 1 -amd 1`.
> 2. GPU PCI Bus ID you can check Device Manager - Display Adapters - Properties - General - Location - PCI Bus.
> 3. Nvidia P-State is 0 or 2, AMD P-State is 2 or 3.
> 4. Nvidia frequency is relative offset from base clock, 100000 will be +100 MHz, AMD frequency is absolute value, 1000000  will be 1000 MHz.
> 
> Working example for my Nvidia GPU at PCI Bus ID 1, +100 MHz core, +500 MHz memory: `nvapioc.exe -nvidia 1 -amd 0 -core 1 0 100000 -mem 1 0 500000`
> 
> Update: AMD core P-State (can be 1, 2, 3) and memory P-State (can be 7) is different, you can check with OverdriveNTool. Nvidia P-State almost always will be 0, you can check with NVIDIA Inspector. Tools links in ReadMe.

Dear Demion, 
Can you tell me if this application will work with RTX 3000 / 4000?

**Comment by Demion** [comment]
Worked fine with GTX 1660 Super and RTX 3060 Ti, should work with RTX 4000, you can give it a try.
Except fan control not working starting with RTX 2000. Fan control fix test build - https://github.com/Demion/nvapioc/issues/2#issuecomment-802307016

**Comment by C3Pool** [comment]
Hi,Demion.
nvapioc.exe -nvidia 1 -amd 0 -mem 9 0 1100000
I use this parameter to control video memory, but it doesn't work. Currently I can only control the fan

**Comment by C3Pool** [comment]
> Hi,Demion. nvapioc.exe -nvidia 1 -amd 0 -mem 9 0 1100000 I use this parameter to control video memory, but it doesn't work. Currently I can only control the fan

![image](https://user-images.githubusercontent.com/44562009/216637344-b4872719-e2a4-4eba-ad29-68460598ca7a.png)

**Comment by Demion** [comment]
Do you test under load? Please provide log file.

**Comment by C3Pool** [comment]
[log.txt](https://github.com/Demion/nvapioc/files/10580184/log.txt)


> 

[log.txt](https://github.com/Demion/nvapioc/files/10580188/log.txt)

**Comment by C3Pool** [comment]
I not using under load

**Comment by Demion** [comment]
No errors in log file.
Without load, at idle, GPU stay in power save mode (P-State 8). Check under load (P-State 0), it should work.

**Comment by C3Pool** [comment]
> No errors in log file. Without load, at idle, GPU stay in power save mode (P-State 8). Check under load (P-State 0), it should work.

Works under load, but remains inactive under no load 
I set nvapioc.exe -nvidia 1 -amd 0 -mem 9 8 1200000 -fan 9 0 80

**Comment by C3Pool** [comment]
[log.txt](https://github.com/Demion/nvapioc/files/10580372/log.txt)

**Comment by Demion** [comment]
I am not sure that overclock functions designed to work with no load at P-State 8.
`NVAPI_NOT_SUPPORTED (-104) Requested feature is not supported in the selected GPU.`

**Comment by C3Pool** [comment]
> I am not sure that overclock functions designed to work with no load at P-State 8. `NVAPI_NOT_SUPPORTED (-104) Requested feature is not supported in the selected GPU.`

ok thanks, so far sure its working fine under load

**Comment by C3Pool** [comment]
How to set parameters if multiple GPUs

**Comment by Demion** [comment]
`nvapioc.exe -mem 1 0 1000000 -mem 2 0 1000000 -mem 3 0 1000000`
1, 2, 3 - GPU PCI Bus ID

**Comment by C3Pool** [comment]
ok thanks
