### ISSUE TITLE
Some questions regarding the code and nvapi. 

### ISSUE THREAD

**Issue by 1usmus** [Demion/nvapioc#11]
Dear Demion,
I have some questions regarding the code and nvapi. 

1) Can you tell me if all 3 functions work?
NvApiSetVoltageOffset
NvApiSetOverVoltageOffset
NvApiSetVoltageLock

2) Apart from obtaining curve data, is it possible to obtain current parameter values? 

3) You don't have a fan control curve implemented, am I correct in assuming that the main reason is a lack of information?

**Comment by Demion** [comment]
Hi. I am not working on this project for years.

`NvApiSetVoltageOffset` and `NvApiSetOverVoltageOffset` not used. 
Probably for older NVIDIA GPUs, reversed from NVIDIA Inspector.
`NvApiSetVoltageLock` actually used in `-cvolt` to set core voltage in microvolts (uV).

Not sure what you mean about curve, but as I remember:
`-curve 0 0` - reset curve to default.
`-curve 0 -1` - save curve to curve.bat file.
`-curve 0 1 1000000 100000` - set curve to +100 MHz at 1000 mV.

If fan control curve is implemented by separate API then, for example, need to reverse MSI Afterburner, to know how it works.
Other than that manual fan control should work, although you need new API starting from RTX 2000 NVIDIA GPU - https://github.com/Demion/nvapioc/issues/2#issuecomment-802307016
`NvAPI_GPU_SetCoolerLevels` RTX 1000 and older, `NvAPI_GPU_ClientFanCoolersSetControl` for RTX 2000 and newer.
