### ISSUE TITLE
Can you upgrade, please

### ISSUE THREAD

**Issue by qq86007801** [Demion/nvapioc#2]
Can you upgrade, please
RTX2070, the graphics card can not adjust the fan

**Comment by Demion** [comment]
Known issue, fan control is not working on new NVIDIA cards starting from 20 series. I will look into it soon.

**Comment by qq86007801** [comment]
Thank you for your reply，Your update is urgently needed

**Comment by Demion** [comment]
You can try new test build. [NvApiOc_v0.8a.zip](https://github.com/Demion/nvapioc/files/6167259/NvApiOc_v0.8a.zip)
`fanIndex` starts from 1 (0 = all fans).
`speed` (-1 = default / auto).

**Comment by qq86007801** [comment]
> 您可以尝试新的测试版本。[NvApiOc_v0.8a.zip](https://github.com/Demion/nvapioc/files/6167259/NvApiOc_v0.8a.zip)
> `fanIndex`从1开始（0 =所有风扇）。
> `speed`（-1 =默认/自动）。

Perfect, in my rx3070
Thank you very much
![微信图片_20210319101009](https://user-images.githubusercontent.com/33634838/111721650-51e1e800-889b-11eb-81db-2452a23e4913.png)

**Comment by Demion** [comment]
For NVIDIA you need to set `pState` 0 (or 2).
`nvapioc -core 0 0 100000 -mem 0 0 500000`

**Comment by qq86007801** [comment]
ok,tank you

**Comment by qq86007801** [comment]
ok,tank you
