### ISSUE TITLE
-power gpuBusId power ?

### ISSUE THREAD

**Issue by qq86007801** [Demion/nvapioc#3]
-power 0 80= 80%power?
-power 0 0 =?
How to control the power
"0"What does it mean

**Comment by qq86007801** [comment]
-power 0 100=200W
-power 0 0 =130W

**Comment by qq86007801** [comment]
RTX2060
-power 0  0  =132W, ETH=31M
-power 0 50 =90W  , ETH=31M
I don't quite understand this parameter

**Comment by Demion** [comment]
`power` is in Power Limit %.
80 = 80%
100 = 100%
0 = not supported, no effect (returns error `NVAPI_INVALID_ARGUMENT = -5` in log file).

**Comment by qq86007801** [comment]
Indeed - 5
Can I replace different API solutions?

**Comment by qq86007801** [comment]
GTX, RTX, can't control power

**Comment by qq86007801** [comment]
GTX, RTX, can't control power

**Comment by Demion** [comment]
Works for me on GTX 10, 16 and RTX 30. 
Limits are same as MSI Afterburner, for example one GPU is 56-108%, another GPU is 50-108%.
What are you trying to achieve (why set power 0) ?

**Comment by qq86007801** [comment]
In win10 NVIDIA gtx1060 rtx2060 rtx3070,
-power 0 80 
return -5
api 440.97🌝🌝

**Comment by qq86007801** [comment]
> 我可以在GTX
> 10、16和RTX 30上使用。限制与MSI Afterburner相同，例如一个GPU为56-108％，另一个GPU为50-108％。
> 您要达到什么目的（为什么将功率设置为0）？

Reduce power consumption

**Comment by qq86007801** [comment]
> Works for me on GTX 10, 16 and RTX 30.
> Limits are same as MSI Afterburner, for example one GPU is 56-108%, another GPU is 50-108%.
> What are you trying to achieve (why set power 0) ?

Reduce power consumption，
however
NVAPI_INVALID_ARGUMENT = -5

**Comment by qq86007801** [comment]
set power 0    Return value -1
set power 75 return value -5
drive 440.97

**Comment by Demion** [comment]
`NvAPI_GPU_ClientPowerPoliciesSetStatus` return -5?
I don't know what is the problem then.
In first post you said power 0 80 works, but power 0 0 does not work? You can not set power 0, or power 80 now not working too?
Show me complete batch file, maybe you are using it wrong.
My driver is 457.51 Win10 64 (but it worked with older drivers too).
-1 = `NVAPI_ERROR` | Generic error.
-5 = `NVAPI_INVALID_ARGUMENT` | The argument/parameter value is not valid or NULL.

**Comment by qq86007801** [comment]
Please give a correct batch template. Thank you

**Comment by qq86007801** [comment]
nvapioc -power 0 80
pause
 
my Batch processing

**Comment by Demion** [comment]
`nvapioc -power 1 60 -power 2 80 -power 3 80`
Set GPU 1 to 60%, GPU 2,3 to 80%.
`nvapioc -power 1 100 -power 2 100 -power 3 100`
Set all GPU 1,2,3 to 100%.
1,2,3 is GPU PCI Bus Id (Device Manager - Display Adapters - Properties - General - Location - PCI Bus).

**Comment by qq86007801** [comment]
> `nvapioc -power 1 60 -power 2 80 -power 3 80`
> Set GPU 1 to 60%, GPU 2,3 to 80%.
> `nvapioc -power 1 100 -power 2 100 -power 3 100`
> Set all GPU 1,2,3 to 100%.
> 1,2,3 is GPU PCI Bus Id (Device Manager - Display Adapters - Properties - General - Location - PCI Bus).

nvapioc -power 0 60 =all bus?

**Comment by Demion** [comment]
No, all API require set for each PCI Bus Id, no option for all GPUs.
I may add -1 in future for all GPUs.

**Comment by qq86007801** [comment]
I finally know what the problem is
Using 457.51, the display card can be controlled by bus 1
In other drivers, I can only use bus0 control
![mmexport1616424336698](https://user-images.githubusercontent.com/33634838/112008836-d0bb7700-8b60-11eb-870a-60665a0dc7b5.png)
![mmexport1616424333892](https://user-images.githubusercontent.com/33634838/112008861-d6b15800-8b60-11eb-9b97-75ccadcf31f8.png)

**Comment by Demion** [comment]
So on 457.51 driver PCI Bus is 1 and on 440.97 it was different?
Anyway you are not using it correctly for core mem and fan you need to specify number for pState (0) and for fanIndex (0).
`nvapioc -core 1 0 100000 -mem 1 0 500000 -power 1 100 -fan 1 0 50`
It is working, only because conversion from wrong parameter is default to 0.
Also, I think, first driver for RTX 3070 is 457.09 and for RTX 3060 Ti is 457.51. 440.97 is 2019 driver.

**Comment by qq86007801** [comment]
replace nvapi.dll=440.97

**Comment by Demion** [comment]
I don't understand why are you trying use power 0 0 when it should be power 1 X. 
I also don't understand why you use different driver / DLL.
1st screenshot you set mem core to 0 GPU (if exist), but power and fan to 1 GPU.
2nd screenshot you set all to 1 GPU, but power 0 0 is just not valid.
I don't know why you getting low consumption, maybe your GPU enters low P State. 
You can check P State with NVIDIA Inspector – Tool.  You can check your current overclock with MSI Afterburner.
Also check your GPU Voltage and Power Consumption (%) in GPU-Z.
I don't advice mixing driver version and different DLL version, may result in unexpected behavior.

**Comment by qq86007801** [comment]
The strange thing is the second one
powe 0 0 Is an incorrect parameter
Let the GPU into a strange state

**Comment by qq86007801** [comment]
It turned out that I replaced the nvapi.dll file, resulting in the mismatch problem

**Comment by qq86007801** [comment]
Accidentally, I found a low-power pattern,On the RTX20, the power is very low and the Hash is not reduced

**Comment by qq86007801** [comment]
I made a mistake using it, resulting in a strange result
![微信图片_20210323180152](https://user-images.githubusercontent.com/33634838/112136844-7e369500-8c0a-11eb-9006-7e7ca49e8e27.png)
![80W](https://user-images.githubusercontent.com/33634838/112136846-7f67c200-8c0a-11eb-8e74-051fe94a3278.png)

**Comment by Demion** [comment]
I already said that I don't know what is the reason. Also I suggested to check all GPU stats, especially P State, Voltage and Power Consumption.

> I don't know why you getting low consumption, maybe your GPU enters low P State.
> You can check P State with NVIDIA Inspector – Tool. You can check your current overclock with MSI Afterburner.
> Also check your GPU Voltage and Power Consumption (%) in GPU-Z.

**Comment by qq86007801** [comment]
> 我已经说过，我不知道是什么原因。我还建议检查所有GPU统计信息，尤其是P状态，电压和功耗。
> 
> > 我不知道为什么您消耗的电量越来越少，也许您的GPU进入了低P状态。
> > 您可以使用NVIDIA Inspector –工具检查P状态。您可以使用MSI Afterburner检查当前的超频。
> > 还要检查GPU-Z中的GPU电压和功耗（％）。

Under the wrong parameters, the gpu-z power is reduced to 80W, and the voltage is almost reduced by half
Beautiful mistake

**Comment by qq86007801** [comment]
> 我已经说过，我不知道是什么原因。我还建议检查所有GPU统计信息，尤其是P状态，电压和功耗。
> 
> > 我不知道为什么您消耗的电量越来越少，也许您的GPU进入了低P状态。
> > 您可以使用NVIDIA Inspector –工具检查P状态。您可以使用MSI Afterburner检查当前的超频。
> > 还要检查GPU-Z中的GPU电压和功耗（％）。



> I already said that I don't know what is the reason. Also I suggested to check all GPU stats, especially P State, Voltage and Power Consumption.
> 
> > I don't know why you getting low consumption, maybe your GPU enters low P State.
> > You can check P State with NVIDIA Inspector – Tool. You can check your current overclock with MSI Afterburner.
> > Also check your GPU Voltage and Power Consumption (%) in GPU-Z.

ok,
With the right parameters, 2070 supports 80% power, can it be lower?

**Comment by Demion** [comment]
It should support at least 60% power. Also you can try `-cvolt` to set low voltage manually. 
Example GPU 1 750 mV: `-cvolt 1 0 750000`

**Comment by qq86007801** [comment]
ok Thank you very much.

**Comment by qq86007801** [comment]
Please add a parameter that supports all graphics cards, such as - 1
PCI bus is different on different motherboards

**Comment by Demion** [comment]
You can try new test build. [NvApiOc_v0.8b.zip](https://github.com/Demion/nvapioc/files/6207717/NvApiOc_v0.8b.zip)
`gpuBusId` parameter for all functions: positive numbers (0 .. 127) = PCI Bus ID, negative numbers (-1 .. -128) = GPU Index.

**Comment by qq86007801** [comment]
Thank you very much for your help. You are a great partner
