### ISSUE TITLE
Not working on win10

### ISSUE THREAD

**Issue by 593749519** [Demion/nvapioc#4]
Nice work! Tested on win10, not working, only take effect when GPU_Z is installed, seems GPU_Z has some trick to turn on overlocking？

**Comment by Demion** [comment]
Nvapioc use `nvapi.dll` / `nvapi64.dll` for NVIDIA, `atiadlxx.dll` / `atiadlxy.dll` for AMD. 
These DLLs should be installed normally with driver. 
Maybe problem can be with DCH (Windows driver package) drivers, they are missing `nvidia-smi` and maybe `nvapi` too.

**Comment by ghost** [comment]
What did you try ?
With which version of NvApiOc ?

As I have a fresh Windows 10 install since yesterday I tried to reproduce your issue.
I just installed the nVidia drivers v461.92 for the GeForce 690M I have on my laptop.
I use GPU Shark to monitor my GPUs instead of GPU-Z because I had a minor issue I don't remember with GPU-Z.

So, if I start GPU Shark, I see
![image](https://user-images.githubusercontent.com/57593477/112973955-29d36e00-9152-11eb-8813-b89e18070f4f.png)

After doing
`nvapioc.exe -core 1 0 10000`
I get
![image](https://user-images.githubusercontent.com/57593477/112974069-54252b80-9152-11eb-8775-44232d1b20b5.png)

After doing
`nvapioc.exe -core 1 0 0`
I get
![image](https://user-images.githubusercontent.com/57593477/112974361-a9613d00-9152-11eb-9a87-0a622798eac9.png)
back.

Fresh Windows 10 install with only the nVidia drivers.

**Comment by 593749519** [comment]
Enviorment:&nbsp;
Notebook dell 7650 I7 7700K
Nvidia 1050Ti
Driver: 378.66 (tried newest 461.92, the same)
Run NvApiOc under administrator privilege, also tried nvidia-smi -rac, not working.
So I guess there are switch on OC, because if GPUZ or AfterBurner installed, then run NvApiOc, all worked!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Demion/nvapioc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 晚上6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Demion/nvapioc] Not working on win10 (#4)





 
What did you try ?
 With which version of NvApiOc ?
 
As I have a fresh Windows 10 install since yesterday I tried to reproduce your issue.
 I just installed the nVidia drivers v461.92 for the GeForce 690M I have on my laptop.
 I use GPU Shark to monitor my GPUs instead of GPU-Z because I had a minor issue I don't remember with GPU-Z.
 
So, if I start GPU Shark, I see
 
 
After doing
 nvapioc.exe -core 1 0 10000
 I get
 
 
After doing
 nvapioc.exe -core 1 0 0
 I get
 
 back.
 
Fresh Windows 10 install with only the nVidia drivers.

**Comment by Demion** [comment]
Where  you download drivers from? As I was saying, DCH version (Windows driver package) might not work.
Also what logs show? `LoadLibraryA` error?

**Comment by 593749519** [comment]
As you say, the driver may be DCH version, but I don't know how to examine if it's DCH version.
NVAPI_get_pstates20 returns NVAPI_ERROR, use nvml, its log shows "oc not supported.“




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Demion/nvapioc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Demion/nvapioc] Not working on win10 (#4)





 
Where  you download drivers from? As I was saying, DCH version (Windows driver package) might not work.
 Also what logs show? LoadLibraryA error?

**Comment by Demion** [comment]
So it seems it manages to load nvapi.dll. Can you post full log?
You can try 457.51 WHQL Win10 x64 (notebook).
https://www.nvidia.com/download/driverResults.aspx/167107/en-us

**Comment by 593749519** [comment]
Wow! The 457.51 driver worked! Thanks!&nbsp;Then the question is how to download a proper driver for overlocking?
And curious why&nbsp;nvidiaInspector and GPUZ can work on both drivers.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Demion/nvapioc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Demion/nvapioc] Not working on win10 (#4)





 
So it seems it manages to load nvapi.dll. Can you post full log?
 You can try 457.51 WHQL Win10 x64 (notebook).
 https://www.nvidia.com/download/driverResults.aspx/167107/en-us

**Comment by Demion** [comment]
I don't know what is the problem. First please provide full log file, maybe something clears up.

**Comment by 593749519** [comment]
With 378.66, the log is:
NVAPI initialization...
Overclocking failed: NVAPI_ERROR [nvoc\nvapi\nvapioc.cpp, frequency_scaling::nvapi_register_gpu, 234] NVAPI register failed. GPU 0 doesnt support OC





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Demion/nvapioc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Demion/nvapioc] Not working on win10 (#4)





 
I don't know what is the problem. First please provide full log file, maybe something clears up.

**Comment by Demion** [comment]
Where do you get this log from? I need log `log.txt` from `nvapioc.exe`.

**Comment by 593749519** [comment]
sorry, the wrong log is sent. will get it right away.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Demion/nvapioc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 凌晨0:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Demion/nvapioc] Not working on win10 (#4)





 
Where do you get this log from? I need log log.txt from nvapioc.exe.

**Comment by 593749519** [comment]
Foget to tell you that I'm using vs2017 to open the source and get the log.txt.
But your compile version is OK. guess its the nvapi64.dll different?

log below:
[01.04.2021 00:50:23][main.cpp:0344] nvapi = LoadLibraryA(nvapiDllName)                                                                     140725363802112      (0x00007FFD2D520000)
[01.04.2021 00:50:23][main.cpp:0350] NvAPI_QueryInterface = (void* (__cdecl*)(unsigned int)) GetProcAddress(nvapi, "nvapi_QueryInterface")  140725364425600      (0x00007FFD2D5B8380)
[01.04.2021 00:50:23][main.cpp:0389] result = NvAPI_Initialize()                                                                            0                    (0x0000000000000000)
[01.04.2021 00:50:23][main.cpp:0428] result = NvAPI_EnumPhysicalGPUs(handles, &count)                                                       0                    (0x0000000000000000)
[01.04.2021 00:50:24][main.cpp:0437] busIdResult = NvAPI_GPU_GetBusId(handles[i], &busId)                                                   0                    (0x0000000000000000)
[01.04.2021 00:50:24][main.cpp:0457] result = NvAPI_EnumTCCPhysicalGPUs(handles, &count)                                                    0                    (0x0000000000000000)
[01.04.2021 00:50:24][main.cpp:0849] adl = LoadLibraryA("atiadlxx.dll")                                                                     0                    (0x0000000000000000)
[01.04.2021 00:50:24][main.cpp:0852] adl = LoadLibraryA("atiadlxy.dll")                                                                     0                    (0x0000000000000000)
[01.04.2021 00:50:37][main.cpp:0493] result = NvAPI_GPU_SetPstates20(NvApiGpuHandles[gpuBusId], &pStatesInfo)                               -1                   (0xFFFFFFFFFFFFFFFF)
[01.04.2021 00:50:41][main.cpp:0401] result = NvAPI_Unload()                                                                                0                    (0x0000000000000000)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Demion/nvapioc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 凌晨0:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Demion/nvapioc] Not working on win10 (#4)





 
Where do you get this log from? I need log log.txt from nvapioc.exe.

**Comment by 593749519** [comment]
The program works just fine!
After some exploration, found 2 curious result:
1. if set breakpoint before overlock, result will be NVAPI_ERROR
2. NvAPI_EnumPhysicalGPUs, NvAPI_GPU_GetBusId, NvAPI_GPU_SetPstates20 must be called in a chain without any delay or break. maybe because the gpu handle is not persistent.
