### ISSUE TITLE
How to use the -curve option?

### ISSUE THREAD

**Issue by macaquinyho** [Demion/nvapioc#6]
Hi, I'm trying to get the curve option working (-core and -mem work on my MX150) but it errors with invalid parameter. 
I input the following: `.\nvapioc.exe -curve 3 -1 -80000 1670000 85000 1690000 86000 1680000`
and the output is:

`Invalid parameter #4 "-80000"`
`Invalid parameter #5 "1670000"`
`Invalid parameter #6 "85000"`
`Invalid parameter #7 "1690000"`
`Invalid parameter #8 "86000"`
`Invalid parameter #9 "1680000"`

By the way, the project can be compiled with mingw-w64 and is working okay

**Comment by Demion** [comment]
`nvapioc -curve 3 0`  reset curve
`nvapioc -curve 3 -1` save current curve to curve.bat file
`nvapioc -curve 3 3 800000 1670000 850000 1690000 860000 1680000`
2nd `3` is curve entry count. Voltage is uV, so probably `800000` not `80000`. Frequency is kHz, but offset, not absolute value, so probably `1670000` is not correct value.
What are you trying to achieve?
