### ISSUE TITLE
Can you lock the core and reduce power consumption like hiveos

### ISSUE THREAD

**Issue by qq86007801** [Demion/nvapioc#8]
Hello friend

See that hiveos has a great setting to lock the GPU frequency

Can you achieve this
![Screenshot_2021-10-15-21-29-01-855_com chrome beta](https://user-images.githubusercontent.com/33634838/137495326-738e14f1-75ce-4848-8a5c-5bfccb66ff1d.jpg)

https://forum.hiveos.farm/t/locked-core-clock-speed-is-much-better-than-power-limit-why-is-not-included-by-default/29803/5

**Comment by Demion** [comment]
You can try voltage lock command. And set core / memory clock offset frequency.
This will set GPU Clock to -500 MHz, GPU Memory Clock to + 800 MHz, GPU Core Voltage to 0.775 V.
`nvapioc -core 1 0 -500000 -mem 1 0 800000  -cvolt 1 0 775000`

**Comment by qq86007801** [comment]
After the test, the parameters took effect, but the power was not reduced
.....-_-!

**Comment by Demion** [comment]
How you check power?
